CREATE TABLE CHIT_CONFIG(id INTEGER PRIMARY KEY AUTOINCREMENT, amt INTEGER, percentage INTEGER, members_count INTEGER);
INSERT INTO CHIT_CONFIG(amt, percentage, members_count) values(500000, 3, 20);

SELECT * FROM chiT_config ORDER BY amt asc;

INSERT INTO MEMBER_CONFIG(name, phone) values('vijay', '+919042307071');
SELECT * FROM MEMBER_CONFIG ORDER BY name ASC;

CREATE TABLE CHIT(id INTEGER PRIMARY KEY AUTOINCREMENT,chit_config_id INTEGER, name VARCHAR, start_date TEXT, chit_date TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(chit_config_id) REFERENCES chit_config(id));

INSERT INTO CHIT(chit_config_id, name, start_date, chit_date) VALUES(1, 'GROUP-B', '1996-09-05', '2020-08-06');
SELECT * FROM CHIT;
SELECT * FROM CHIT WHERE chit_date >= CURRENT_TIMESTAMP;